version: 2.1

jobs:
  build:
    working_directory: ~/elmish

    docker:
    - image: circleci/node:10.15.3-stretch

    parallelism: 1

    steps:
    - checkout: { path: "~/elmish" }

    - restore_cache:
        keys:
          - elmish-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "bower.json" }}
          - elmish-{{ .Branch }}-

    - run: npm install && npm run build

    - save_cache:
        key: elmish-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "bower.json" }}
        paths:
          - bower_components
          - node_modules
          - output
          - ~/.cache
