// For now, we are using a local copy of react-html-attributes.
// Eventually, the relative path here should be removed, and
// the version number of react-html-attributes should be bumped.
module.exports.props = require("./react-html-attributes")

module.exports.voids = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]
// The types for certain attributes differ according to their containing element.
// These appear in the typesByElement object, using "*" as a default element
// (required only if the default attribute type is other than `String`).
// For clarity, it is an error for any attribute to be in both `types` and `typesByElement`.
module.exports.typesByElement = {
  cols: {
    textarea: "Int",
  },
  max: {
    meter: "Number",
    progress: "Number",
  },
  min: {
    meter: "Number",
  },
  rows: {
    textarea: "Int",
  },
  size: {
    input: "Int",
    select: "Int",
  },
}
module.exports.types = {
  allowFullScreen: "Boolean",
  allowTransparency: "Boolean",
  async: "Boolean",
  autoComplete: "Boolean",
  autoFocus: "Boolean",
  autoPlay: "Boolean",
  capture: "Boolean",
  checked: "Boolean",
  children: "Array ReactElement",
  colSpan: "Int",
  contentEditable: "Boolean",
  controls: "Boolean",
  dangerouslySetInnerHTML: "{ __html :: String }",
  default: "Boolean",
  defer: "Boolean",
  disabled: "Boolean",
  draggable: "Boolean",
  formNoValidate: "Boolean",
  hidden: "Boolean",
  itemScope: "Boolean",
  loop: "Boolean",
  maxLength: "Int",
  minLength: "Int",
  multiple: "Boolean",
  muted: "Boolean",
  noValidate: "Boolean",
  // TODO: Replace `JsCallback0` with better representation:
  onBlur: "JsCallback0",
  onChange: "JsCallback0",
  onClick: "JsCallback0",
  onFocus: "JsCallback0",
  onInput: "JsCallback0",
  onInvalid: "JsCallback0",
  onKeyDown: "JsCallback0",
  onKeyPress: "JsCallback0",
  onKeyUp: "JsCallback0",
  onMouseDown: "JsCallback0",
  onMouseEnter: "JsCallback0",
  onMouseLeave: "JsCallback0",
  onMouseMove: "JsCallback0",
  onMouseOut: "JsCallback0",
  onMouseOver: "JsCallback0",
  onMouseUp: "JsCallback0",
  onSubmit: "JsCallback0",
  open: "Boolean",
  playsInline: "Boolean",
  readOnly: "Boolean",
  ref: "Ref (Nullable Node)",
  required: "Boolean",
  reversed: "Boolean",
  rowSpan: "Int",
  scoped: "Boolean",
  seamless: "Boolean",
  selected: "Boolean",
  span: "Int",
  spellCheck: "Boolean",
  srcDoc: "ReactElement",
  start: "Int",
  style: "CSS",
  suppressContentEditableWarning: "Boolean",
  tabIndex: "Int",
  unselectable: "Boolean",
}
module.exports.reserved = [
  "module",
  "data",
  "type",
  "newtype",
  "class",
  "instance",
  "where",
  "derive",
  "if",
  "then",
  "else",
  "case",
  "of",
]
